// Hacker-themed terminal themes
export const themes = {
  matrix: {
    name: 'Matrix',
    description: 'Classic green-on-black hacker aesthetic',
    background: '#0d0d0d',
    foreground: '#00ff00',
    cursor: '#00ff00',
    selection: 'rgba(0, 255, 0, 0.3)',
    prompt: '#00cc00',
    comment: '#006600',
    accent: '#33ff33',
    windowBg: '#0a0a0a',
    windowBorder: '#00ff00',
    titleBar: '#1a1a1a',
    buttonRed: '#ff5f56',
    buttonYellow: '#ffbd2e',
    buttonGreen: '#27c93f',
    glow: true,
    scanlines: true,
  },
  cyberpunk: {
    name: 'Cyberpunk',
    description: 'Neon pink and cyan vibes',
    background: '#0d0221',
    foreground: '#ff00ff',
    cursor: '#00ffff',
    selection: 'rgba(255, 0, 255, 0.3)',
    prompt: '#00ffff',
    comment: '#ff6ec7',
    accent: '#ffff00',
    windowBg: '#0a0118',
    windowBorder: '#ff00ff',
    titleBar: '#1a0533',
    buttonRed: '#ff2a6d',
    buttonYellow: '#ffff00',
    buttonGreen: '#00ffff',
    glow: true,
    scanlines: false,
  },
  hacker: {
    name: 'Mr. Robot',
    description: 'Dark theme inspired by fsociety',
    background: '#0c0c0c',
    foreground: '#b5e853',
    cursor: '#b5e853',
    selection: 'rgba(181, 232, 83, 0.3)',
    prompt: '#ffffff',
    comment: '#6a9955',
    accent: '#e85353',
    windowBg: '#080808',
    windowBorder: '#333333',
    titleBar: '#1e1e1e',
    buttonRed: '#e85353',
    buttonYellow: '#e8b953',
    buttonGreen: '#b5e853',
    glow: false,
    scanlines: false,
  },
  dracula: {
    name: 'Dracula',
    description: 'Popular dark theme with purple accents',
    background: '#282a36',
    foreground: '#f8f8f2',
    cursor: '#f8f8f2',
    selection: 'rgba(68, 71, 90, 0.5)',
    prompt: '#bd93f9',
    comment: '#6272a4',
    accent: '#ff79c6',
    windowBg: '#21222c',
    windowBorder: '#44475a',
    titleBar: '#343746',
    buttonRed: '#ff5555',
    buttonYellow: '#f1fa8c',
    buttonGreen: '#50fa7b',
    glow: false,
    scanlines: false,
  },
  synthwave: {
    name: 'Synthwave',
    description: '80s retro futuristic vibes',
    background: '#2b213a',
    foreground: '#ff7edb',
    cursor: '#72f1b8',
    selection: 'rgba(114, 241, 184, 0.3)',
    prompt: '#72f1b8',
    comment: '#848bbd',
    accent: '#fede5d',
    windowBg: '#241b2f',
    windowBorder: '#ff7edb',
    titleBar: '#34294f',
    buttonRed: '#fe4450',
    buttonYellow: '#fede5d',
    buttonGreen: '#72f1b8',
    glow: true,
    scanlines: true,
  },
  nord: {
    name: 'Nord',
    description: 'Cool arctic blue palette',
    background: '#2e3440',
    foreground: '#d8dee9',
    cursor: '#88c0d0',
    selection: 'rgba(136, 192, 208, 0.3)',
    prompt: '#88c0d0',
    comment: '#616e88',
    accent: '#81a1c1',
    windowBg: '#242933',
    windowBorder: '#4c566a',
    titleBar: '#3b4252',
    buttonRed: '#bf616a',
    buttonYellow: '#ebcb8b',
    buttonGreen: '#a3be8c',
    glow: false,
    scanlines: false,
  },
  retroGreen: {
    name: 'Retro CRT',
    description: 'Old school phosphor monitor',
    background: '#0c1e0c',
    foreground: '#33ff33',
    cursor: '#33ff33',
    selection: 'rgba(51, 255, 51, 0.3)',
    prompt: '#66ff66',
    comment: '#1a8c1a',
    accent: '#99ff99',
    windowBg: '#0a1a0a',
    windowBorder: '#33ff33',
    titleBar: '#0f2e0f',
    buttonRed: '#ff3333',
    buttonYellow: '#ffff33',
    buttonGreen: '#33ff33',
    glow: true,
    scanlines: true,
    crt: true,
  },
  amber: {
    name: 'Amber Mono',
    description: 'Classic amber monochrome display',
    background: '#1a1400',
    foreground: '#ffb000',
    cursor: '#ffb000',
    selection: 'rgba(255, 176, 0, 0.3)',
    prompt: '#ffc000',
    comment: '#996600',
    accent: '#ffd700',
    windowBg: '#140f00',
    windowBorder: '#ffb000',
    titleBar: '#2a1f00',
    buttonRed: '#ff6600',
    buttonYellow: '#ffb000',
    buttonGreen: '#ffd700',
    glow: true,
    scanlines: true,
    crt: true,
  },
  midnight: {
    name: 'Midnight',
    description: 'Deep blue hacker theme',
    background: '#0a0e14',
    foreground: '#b3b1ad',
    cursor: '#e6b450',
    selection: 'rgba(230, 180, 80, 0.3)',
    prompt: '#59c2ff',
    comment: '#626a73',
    accent: '#e6b450',
    windowBg: '#070a0e',
    windowBorder: '#1f2430',
    titleBar: '#0d1017',
    buttonRed: '#f07178',
    buttonYellow: '#e6b450',
    buttonGreen: '#c2d94c',
    glow: false,
    scanlines: false,
  },
  tokyo: {
    name: 'Tokyo Night',
    description: 'Inspired by Tokyo city lights',
    background: '#1a1b26',
    foreground: '#c0caf5',
    cursor: '#c0caf5',
    selection: 'rgba(192, 202, 245, 0.2)',
    prompt: '#7aa2f7',
    comment: '#565f89',
    accent: '#bb9af7',
    windowBg: '#16161e',
    windowBorder: '#27293a',
    titleBar: '#1f2335',
    buttonRed: '#f7768e',
    buttonYellow: '#e0af68',
    buttonGreen: '#9ece6a',
    glow: false,
    scanlines: false,
  },
  bloodMoon: {
    name: 'Blood Moon',
    description: 'Dark red hacker aesthetic',
    background: '#10080a',
    foreground: '#ff4444',
    cursor: '#ff6666',
    selection: 'rgba(255, 68, 68, 0.3)',
    prompt: '#ff8888',
    comment: '#662222',
    accent: '#ffaaaa',
    windowBg: '#0c0608',
    windowBorder: '#ff4444',
    titleBar: '#1a0c10',
    buttonRed: '#ff4444',
    buttonYellow: '#ff8844',
    buttonGreen: '#44ff44',
    glow: true,
    scanlines: true,
  },
  ghostInShell: {
    name: 'Ghost Shell',
    description: 'Cyber teal inspired by anime',
    background: '#0a1612',
    foreground: '#00d4aa',
    cursor: '#00ffcc',
    selection: 'rgba(0, 212, 170, 0.3)',
    prompt: '#00ffcc',
    comment: '#006655',
    accent: '#66ffdd',
    windowBg: '#081210',
    windowBorder: '#00d4aa',
    titleBar: '#0c1a16',
    buttonRed: '#ff5566',
    buttonYellow: '#ffcc00',
    buttonGreen: '#00d4aa',
    glow: true,
    scanlines: false,
  },
  monokai: {
    name: 'Monokai Pro',
    description: 'Iconic sublime text theme',
    background: '#2d2a2e',
    foreground: '#fcfcfa',
    cursor: '#fcfcfa',
    selection: 'rgba(252, 252, 250, 0.2)',
    prompt: '#a9dc76',
    comment: '#727072',
    accent: '#ffd866',
    windowBg: '#221f22',
    windowBorder: '#403e41',
    titleBar: '#2d2a2e',
    buttonRed: '#ff6188',
    buttonYellow: '#ffd866',
    buttonGreen: '#a9dc76',
    glow: false,
    scanlines: false,
  },
  catppuccin: {
    name: 'Catppuccin',
    description: 'Soothing pastel mocha theme',
    background: '#1e1e2e',
    foreground: '#cdd6f4',
    cursor: '#f5e0dc',
    selection: 'rgba(205, 214, 244, 0.2)',
    prompt: '#cba6f7',
    comment: '#6c7086',
    accent: '#f5c2e7',
    windowBg: '#181825',
    windowBorder: '#313244',
    titleBar: '#1e1e2e',
    buttonRed: '#f38ba8',
    buttonYellow: '#f9e2af',
    buttonGreen: '#a6e3a1',
    glow: false,
    scanlines: false,
  },
  gruvbox: {
    name: 'Gruvbox',
    description: 'Retro earthy groove',
    background: '#282828',
    foreground: '#ebdbb2',
    cursor: '#ebdbb2',
    selection: 'rgba(235, 219, 178, 0.2)',
    prompt: '#b8bb26',
    comment: '#928374',
    accent: '#fabd2f',
    windowBg: '#1d2021',
    windowBorder: '#3c3836',
    titleBar: '#282828',
    buttonRed: '#fb4934',
    buttonYellow: '#fabd2f',
    buttonGreen: '#b8bb26',
    glow: false,
    scanlines: false,
  },
  oneDark: {
    name: 'One Dark',
    description: 'Atom editor inspired theme',
    background: '#282c34',
    foreground: '#abb2bf',
    cursor: '#528bff',
    selection: 'rgba(171, 178, 191, 0.2)',
    prompt: '#61afef',
    comment: '#5c6370',
    accent: '#c678dd',
    windowBg: '#21252b',
    windowBorder: '#3e4451',
    titleBar: '#282c34',
    buttonRed: '#e06c75',
    buttonYellow: '#e5c07b',
    buttonGreen: '#98c379',
    glow: false,
    scanlines: false,
  },
  anonymous: {
    name: 'Anonymous',
    description: 'Inspired by the hacker collective',
    background: '#0a0a0a',
    foreground: '#39ff14',
    cursor: '#39ff14',
    selection: 'rgba(57, 255, 20, 0.2)',
    prompt: '#ffffff',
    comment: '#1a5c0f',
    accent: '#00ff41',
    windowBg: '#050505',
    windowBorder: '#39ff14',
    titleBar: '#0f0f0f',
    buttonRed: '#ff0000',
    buttonYellow: '#39ff14',
    buttonGreen: '#00ff00',
    glow: true,
    scanlines: true,
    crt: true,
  },
  hackerNews: {
    name: 'Hacker News',
    description: 'YC orange hacker vibes',
    background: '#0d0d0d',
    foreground: '#ff6600',
    cursor: '#ff6600',
    selection: 'rgba(255, 102, 0, 0.3)',
    prompt: '#ffffff',
    comment: '#805300',
    accent: '#ffaa00',
    windowBg: '#080808',
    windowBorder: '#ff6600',
    titleBar: '#141414',
    buttonRed: '#ff6600',
    buttonYellow: '#ffaa00',
    buttonGreen: '#00ff00',
    glow: true,
    scanlines: false,
  },
  solarized: {
    name: 'Solarized Dark',
    description: 'Precision colors for visibility',
    background: '#002b36',
    foreground: '#839496',
    cursor: '#839496',
    selection: 'rgba(131, 148, 150, 0.2)',
    prompt: '#268bd2',
    comment: '#586e75',
    accent: '#b58900',
    windowBg: '#001e26',
    windowBorder: '#073642',
    titleBar: '#002b36',
    buttonRed: '#dc322f',
    buttonYellow: '#b58900',
    buttonGreen: '#859900',
    glow: false,
    scanlines: false,
  },
  hackerPro: {
    name: 'Hacker Pro',
    description: 'Elite coding aesthetic',
    background: '#0b0b0b',
    foreground: '#00ff9c',
    cursor: '#00ff9c',
    selection: 'rgba(0, 255, 156, 0.2)',
    prompt: '#00d4ff',
    comment: '#007a5a',
    accent: '#ff00ff',
    windowBg: '#060606',
    windowBorder: '#00ff9c',
    titleBar: '#101010',
    buttonRed: '#ff0055',
    buttonYellow: '#ffff00',
    buttonGreen: '#00ff9c',
    glow: true,
    scanlines: true,
  },
  vscode: {
    name: 'VS Code Dark+',
    description: 'Official VS Code dark theme',
    background: '#1e1e1e',
    foreground: '#d4d4d4',
    cursor: '#aeafad',
    selection: 'rgba(212, 212, 212, 0.2)',
    prompt: '#569cd6',
    comment: '#6a9955',
    accent: '#ce9178',
    windowBg: '#181818',
    windowBorder: '#3c3c3c',
    titleBar: '#252526',
    buttonRed: '#f14c4c',
    buttonYellow: '#cca700',
    buttonGreen: '#89d185',
    glow: false,
    scanlines: false,
  },
  ayu: {
    name: 'Ayu Dark',
    description: 'Simple, bright colors on dark',
    background: '#0b0e14',
    foreground: '#bfbdb6',
    cursor: '#e6b450',
    selection: 'rgba(230, 180, 80, 0.2)',
    prompt: '#ffb454',
    comment: '#636a72',
    accent: '#e6b450',
    windowBg: '#0d1017',
    windowBorder: '#1a1f29',
    titleBar: '#0f131a',
    buttonRed: '#f07178',
    buttonYellow: '#ffb454',
    buttonGreen: '#aad94c',
    glow: false,
    scanlines: false,
  },
  palenight: {
    name: 'Palenight',
    description: 'Material palenight aesthetic',
    background: '#292d3e',
    foreground: '#a6accd',
    cursor: '#ffcc00',
    selection: 'rgba(166, 172, 205, 0.2)',
    prompt: '#82aaff',
    comment: '#676e95',
    accent: '#c792ea',
    windowBg: '#232635',
    windowBorder: '#3a3f58',
    titleBar: '#292d3e',
    buttonRed: '#ff5370',
    buttonYellow: '#ffcb6b',
    buttonGreen: '#c3e88d',
    glow: false,
    scanlines: false,
  },
  horizon: {
    name: 'Horizon',
    description: 'Warm dark theme with pink accent',
    background: '#1c1e26',
    foreground: '#d5d8da',
    cursor: '#e95678',
    selection: 'rgba(229, 86, 120, 0.2)',
    prompt: '#e95678',
    comment: '#6c6f93',
    accent: '#fab795',
    windowBg: '#16181e',
    windowBorder: '#2e303e',
    titleBar: '#1c1e26',
    buttonRed: '#e95678',
    buttonYellow: '#fab795',
    buttonGreen: '#29d398',
    glow: false,
    scanlines: false,
  },
};

export const fonts = [
  { name: 'JetBrains Mono', value: "'JetBrains Mono', monospace" },
  { name: 'Fira Code', value: "'Fira Code', monospace" },
  { name: 'Source Code Pro', value: "'Source Code Pro', monospace" },
  { name: 'Monaco', value: "'Monaco', monospace" },
  { name: 'Consolas', value: "'Consolas', monospace" },
  { name: 'Courier New', value: "'Courier New', monospace" },
];

export const cursorStyles = [
  { name: 'Block', value: 'block' },
  { name: 'Underline', value: 'underline' },
  { name: 'Bar', value: 'bar' },
];

// Prompt presets for different Linux distros and styles
export const promptPresets = {
  basic: {
    name: 'Basic',
    prompt: '$ ',
    preview: '$ command',
  },
  parrot: {
    name: 'Parrot OS',
    prompt: '┌──(user㉿parrot)-[~]\n└─$ ',
    preview: '┌──(user㉿parrot)-[~]\n└─$',
  },
  kali: {
    name: 'Kali Linux',
    prompt: '┌──(root㉿kali)-[~]\n└─# ',
    preview: '┌──(root㉿kali)-[~]\n└─#',
  },
  htb: {
    name: 'Hack The Box',
    prompt: '[★]──[user@htb]──[~]$ ',
    preview: '[★]──[user@htb]──[~]$',
  },
  arch: {
    name: 'Arch Linux',
    prompt: '[user@arch ~]$ ',
    preview: '[user@arch ~]$',
  },
  ubuntu: {
    name: 'Ubuntu',
    prompt: 'user@ubuntu:~$ ',
    preview: 'user@ubuntu:~$',
  },
  zsh: {
    name: 'Oh My Zsh',
    prompt: '➜ ~ ',
    preview: '➜ ~ git:(main)',
  },
  powershell: {
    name: 'PowerShell',
    prompt: 'PS C:\\> ',
    preview: 'PS C:\\Users\\>',
  },
  minimal: {
    name: 'Minimal',
    prompt: '> ',
    preview: '> command',
  },
  root: {
    name: 'Root',
    prompt: '# ',
    preview: '# sudo command',
  },
  lambda: {
    name: 'Lambda',
    prompt: 'λ ',
    preview: 'λ functional',
  },
  arrow: {
    name: 'Arrow',
    prompt: '❯ ',
    preview: '❯ modern',
  },
};

export const defaultConfig = {
  theme: 'hacker',
  font: fonts[0].value,
  fontSize: 16,
  lineHeight: 1.6,
  typingSpeed: 50,
  cursorStyle: 'block',
  cursorBlink: true,
  showPrompt: true,
  promptText: '$ ',
  promptStyle: 'basic',
  showWindowControls: true,
  showTitle: true,
  title: 'Terminal',
  glowEffect: false,
  scanlineEffect: false,
  crtEffect: false,
  padding: 20,
  borderRadius: 12,
  backgroundImage: null,
  backgroundOpacity: 0.1,
  // Output mode: 'typing' = character by character, 'instant' = all at once
  outputMode: 'typing',
};
